### ISSUE TITLE
Queries with limit does not return any cursor

### ISSUE THREAD

**Issue by leocabral** [feroult/yawp#42]
If we send a query param with limit (/endpoint/?q={"limit": 3}) it does not return any cursor in the results json... it would be nice to have it :wink:

**Comment by leocabral** [comment]
@matheusmr13

**Comment by feroult** [comment]
Today the solution is to work with an Action and the Java API.

Planning to work on this issue soon..

[ ]s

**Comment by luanpotter** [comment]
Fix 0402b9

Currently the solution is this:

* Pass an empty string 'cursor' inside the `q` json to the server, so that a cursor is returned (I made it this way for backwards compatibility);
* If that is done, the return structure will change: instead of an array of results, it will be an object, with the results array as a member (`results`) and a second element, `cursor`, that is the cursor for the next query;
* For the following queries, pass the cursor string recieved in the cursor element of the q object.

Something like this:

    String cursor = "";
    for (int i = 0; i < total; i += limit) {
        String json = get("/parents", params("q", "{ limit: " + limit + ", cursor: '" + cursor + "' }"));
        process(asJsonObject(json).get("results")); // process
        cursor = asJsonObject(json).get("cursor").getAsString(); // next cursor
    }

If @feroult, @leocabral or @matheusmr13 see a better way to do it without breaking the previous API, please care to comment :)

**Comment by feroult** [comment]
@luanpotter, I think this is a pretty good solution, not only for back compatibility. :dart:
